name: Benchmark Baseline

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  baseline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run benchmark
      run: cargo bench -- --save-baseline main --quiet

    - name: Upload baseline
      uses: actions/upload-artifact@v4
      with:
        name: criterion-baseline
        path: target/criterion
        retention-days: 90
