name: CI

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install coverage tool
      run: cargo install cargo-llvm-cov
    - name: Run tests
      run: cargo test:cov

  benchmark_throughput:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Switch to main baseline
      run: git switch main

    - name: Throughput baseline
      run: cargo bench --bench throughput -- --save-baseline main --quiet

    - name: Switch to PR branch
      run: git switch ${{ github.head_ref }}

    - name: Throughput (PR vs main)
      run: cargo bench --bench throughput -- --baseline main

  benchmark_ycsb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Switch to main baseline
      run: git switch main

    - name: YCSB baseline
      run: cargo bench --bench ycsb -- --save-baseline main --quiet

    - name: Switch to PR branch
      run: git switch ${{ github.head_ref }}

    - name: YCSB (PR vs main)
      run: cargo bench --bench ycsb -- --baseline main
